<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Semua Fitur</name>
   <tag></tag>
   <elementGuidId>02e273a3-a0cc-4767-a129-4804fa89275f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='all-features']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.d-none.d-md-inline-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f70baf5-7998-4dfa-bb8f-a41da1f3d0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-inline-block</value>
      <webElementGuid>93e70770-b3f6-49a3-bfec-441273b5e1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semua Fitur</value>
      <webElementGuid>f83c6ce3-2ad1-4147-a531-df14031eacd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all-features&quot;)/span[@class=&quot;d-none d-md-inline-block&quot;]</value>
      <webElementGuid>01a0bcc8-1766-4c74-a65b-16b20b7028cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='all-features']/span</value>
      <webElementGuid>1c8aa090-5de7-46f7-a5ce-6bf553fed1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>230de04a-b3b9-4906-b5ad-99ffa358dfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Semua Fitur' or . = 'Semua Fitur')]</value>
      <webElementGuid>e27ca6d5-a3df-4451-8f5e-f1205aa4b170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
