<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Thumbnail_thumbnailFile</name>
   <tag></tag>
   <elementGuidId>9c8ddf92-833c-4bf5-9785-7e4f336a9007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thumbnailAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='thumbnailAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>051ecca4-17f4-41d3-8262-e2a9d93b89a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a118b10c-2ffa-4b5a-b3cb-5192cf448324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e7f69836-0c0f-4405-9c6b-f193281f833c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thumbnailAdd</value>
      <webElementGuid>9e6c1803-05cc-45fe-a147-29eac684e9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thumbnailFile</value>
      <webElementGuid>3a0cbe46-3b61-4755-9c86-6c031103f42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>9793a7cf-62f4-4df1-8cf7-c7789ab080e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thumbnailAdd&quot;)</value>
      <webElementGuid>1c518335-77aa-450b-97f0-dbcf75fda2ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='thumbnailAdd']</value>
      <webElementGuid>2c1af8c9-c93b-406a-b16a-338187108365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddLarge']/div[2]/div[3]/input</value>
      <webElementGuid>71a5d809-df17-447b-9583-c13acbead145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>db28d599-7093-443a-87eb-5550f4ff0d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'thumbnailAdd' and @name = 'thumbnailFile']</value>
      <webElementGuid>2f4b18f4-967d-4ff4-99a2-3f564afada1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
