<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>35dd33cc-b316-4ac1-a7f4-096a69e40452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.ql-blank > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='quillAreaAdd']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>eae02e7b-9c9c-429b-ae26-f26036da20a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quillAreaAdd&quot;)/div[@class=&quot;ql-editor ql-blank&quot;]/p[1]</value>
      <webElementGuid>24ba0773-df15-41c1-a8cd-52829313ded8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quillAreaAdd']/div/p</value>
      <webElementGuid>4d6ae484-6ca5-4916-adef-d0bface7db54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>337c2b43-fd27-48e3-ac58-2146bc8273eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
