<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_summary</name>
   <tag></tag>
   <elementGuidId>4bbb6ac6-46b1-4d52-aab8-e08483889268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#summaryAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='summaryAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5c089260-ab43-4a82-a302-5e372c53b388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0a5b8c97-bd1c-452a-a8a6-aa38d6481b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>f14472ad-e607-4404-bbaf-1897c1d35e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>summaryAdd</value>
      <webElementGuid>9a5234dc-cac2-4d4a-9edf-1b472d13d4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6ceee3ff-e73e-42ec-9907-23ce8e3acb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;summaryAdd&quot;)</value>
      <webElementGuid>f7d1989b-1686-48f3-affa-34d0eb95b82f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='summaryAdd']</value>
      <webElementGuid>5905da8c-7e46-4f12-b286-2cf7adfc0d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddLarge']/div[2]/div[4]/textarea</value>
      <webElementGuid>067d6ba7-139e-454c-951e-e79ee5d88023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6a429d9b-7063-4e27-8aad-56c4caa56474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'summary' and @id = 'summaryAdd']</value>
      <webElementGuid>548f94de-8bc2-4850-9251-8287baa422c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
