<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log In</name>
   <tag></tag>
   <elementGuidId>8e3d36f6-c310-4f61-bfc9-07407a12ad75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.sl-btn.w-100.my-4.d-flex</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a127ec2b-0824-4865-b1a6-8ec07471b56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f08f46f4-ebfd-4960-9cee-b7d696d6f3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary sl-btn w-100 my-4 d-flex</value>
      <webElementGuid>34e05d9b-0225-4a67-98e7-0053deb8f880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>65213920-d08d-4def-8751-0e0a045dce7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;d-flex flex-column justify-content-between h-100&quot;]/div[@class=&quot;position-relative pb-5&quot;]/div[@class=&quot;position-relative h-100 mb-4&quot;]/div[@class=&quot;position-relative z-2&quot;]/div[@class=&quot;container px-0&quot;]/div[@class=&quot;d-flex align-items-top align-items-sm-center bg-grey-50 p-4 max-w-368 min-h-400&quot;]/div[@class=&quot;w-100&quot;]/button[@class=&quot;btn btn-primary sl-btn w-100 my-4 d-flex&quot;]</value>
      <webElementGuid>0d6bdb6e-d68a-4953-937f-9f5054ed65d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>e8e4960d-af8a-42c3-943f-00c1c8af9df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>f6d69580-91e0-4ed5-a3aa-667f8304ac69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/button</value>
      <webElementGuid>e3642a96-6893-4f17-821a-10d5ab3ea789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>1f53a95f-295d-4d56-9422-991a601186ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
