<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pejabat 1</name>
   <tag></tag>
   <elementGuidId>b78c0333-c0a1-4cfb-90f7-cc32003381eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-roleAdd-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-roleAdd-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b0e3db81-db02-4a4c-a331-1e42fad61d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b3ac9169-7bc5-4588-bdc4-6e6a409dbd04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-roleAdd-container</value>
      <webElementGuid>21dc5991-9367-41a6-9bea-7d1818b7ca71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pejabat 1</value>
      <webElementGuid>ef611ae9-f6c1-49a2-a4f5-bb373dde7eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pejabat 1</value>
      <webElementGuid>5ce7acfe-d64d-4b27-9eb3-e14a3ff38fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-roleAdd-container&quot;)</value>
      <webElementGuid>bc07841b-fb7a-421c-b30b-6eb10fcb9314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-roleAdd-container']</value>
      <webElementGuid>e646a304-d4de-4fe2-a391-72ff5a734b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/span/span/span/span</value>
      <webElementGuid>5d13b93a-5148-478d-ba66-09896956254d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>9352190c-3e7b-4e72-a60b-df64ff98d611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-roleAdd-container' and @title = 'Pejabat 1' and (text() = 'Pejabat 1' or . = 'Pejabat 1')]</value>
      <webElementGuid>42f8b4a7-cb2d-4c31-839a-b29b1a16062f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
