<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Choose Role --</name>
   <tag></tag>
   <elementGuidId>385bc05d-312a-4227-ad76-49daab680572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-roleAdd-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-roleAdd-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>de0258b0-f398-41f8-bdcb-11056e541f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>687f2541-263c-4d90-997c-b4ff62443896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-roleAdd-container</value>
      <webElementGuid>340bab5e-974f-4dfb-a630-66742bca3567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Role --</value>
      <webElementGuid>6fefc86e-5716-4180-9e8f-2efc4246d0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-roleAdd-container&quot;)</value>
      <webElementGuid>d42380f9-ecd1-4714-8158-f368c49b347c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-roleAdd-container']</value>
      <webElementGuid>64dd4297-a073-4757-84b8-3e41399c1710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/span/span/span/span</value>
      <webElementGuid>3cc082c7-599e-4b81-96e8-bbbcf7103cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>701c6de9-7404-4b80-93a6-1a3ceb3ddab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-roleAdd-container' and (text() = '-- Choose Role --' or . = '-- Choose Role --')]</value>
      <webElementGuid>6015444a-83a8-4a98-972d-87b3da228c9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
