<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label 2</name>
   <tag></tag>
   <elementGuidId>ce20f513-b49a-4039-9205-3ad802736ab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='privilege-table']/tbody/tr[2]/td[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.even > td.text-center > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>16512f6b-b83f-4fd0-a848-08b0598cc3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privilege-table&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;text-center&quot;]/label[1]</value>
      <webElementGuid>9841d8fe-baf6-48c7-814a-8d25fcfaaf13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='privilege-table']/tbody/tr[2]/td[2]/label</value>
      <webElementGuid>4112c2fe-2ecc-4a27-9bab-c5a13fc7b4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/label</value>
      <webElementGuid>cc397c1a-77cb-4c26-ab7a-d56336d5d0f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
