<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>235b5c73-0170-45a3-884b-5c39947eda5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='quillAreaAdd']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.ql-blank > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7d091975-1f7c-40a3-8f90-8d931e943d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quillAreaAdd&quot;)/div[@class=&quot;ql-editor ql-blank&quot;]/p[1]</value>
      <webElementGuid>6244153e-1187-4934-8c29-bb9d0669f5b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quillAreaAdd']/div/p</value>
      <webElementGuid>d87427b9-cb53-40eb-b9f0-5a7dc7b4fd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>49ee6b9e-1f29-413a-871c-d68351ebab9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
