<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Name_btnPrivileges</name>
   <tag></tag>
   <elementGuidId>81b582a0-9e3b-4194-8dc3-4feab9528af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnPrivileges']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnPrivileges</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df43ff2f-d033-4eda-bd5b-3946482927a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://34.128.87.8:8082/roles/privileges/7c248e7a-06b8-4909-8f3d-eb2f119a7866</value>
      <webElementGuid>a8d679af-0c02-478f-bd7b-b29618424bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-xs btn-pill</value>
      <webElementGuid>96eef15e-dbc7-4208-a57a-dc3313665540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPrivileges</value>
      <webElementGuid>b062bd27-382f-4e9b-bf02-ccd53166bf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Set Privileges</value>
      <webElementGuid>dbb0160e-24af-4785-b696-ffcb243d3229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@id=&quot;btnPrivileges&quot;]</value>
      <webElementGuid>9d21ac05-4a48-47d6-9ce5-6c1030a11134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnPrivileges']</value>
      <webElementGuid>c01a5f83-78c4-4763-942e-790c88c41d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='role-table']/tbody/tr/td/a</value>
      <webElementGuid>204b1a0b-eac4-4095-8d21-719938f01bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://34.128.87.8:8082/roles/privileges/7c248e7a-06b8-4909-8f3d-eb2f119a7866']</value>
      <webElementGuid>351a5038-3c1e-493f-9c51-be1eb9661204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>cf94d455-82dc-425b-9481-b82e5449cf71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://34.128.87.8:8082/roles/privileges/7c248e7a-06b8-4909-8f3d-eb2f119a7866' and @id = 'btnPrivileges' and @title = 'Set Privileges']</value>
      <webElementGuid>f90cfb3b-87da-40ba-a4c4-af606cf322e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
