<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Choose Role --</name>
   <tag></tag>
   <elementGuidId>9a43f562-5146-4c12-bc32-fea34ede0832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-roleAdd-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-roleAdd-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6dcf31c0-b89f-444b-aa1b-30078a403a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ec2769b0-1c2b-46a0-9564-78eb5b690917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-roleAdd-container</value>
      <webElementGuid>2b04699d-2998-49b3-9650-e028defa064c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Role --</value>
      <webElementGuid>52d24bd7-be48-44d5-9973-44e62ce1f855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-roleAdd-container&quot;)</value>
      <webElementGuid>60042b4f-519b-4d05-8265-dd194dda4f1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-roleAdd-container']</value>
      <webElementGuid>d39b8dd9-e24f-431d-941e-faa67df12402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/span/span/span/span</value>
      <webElementGuid>851ef837-5a91-4436-8d9b-32ed56b7a0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>f9df5a50-040d-4c67-bf2b-4516a83b46bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-roleAdd-container' and (text() = '-- Choose Role --' or . = '-- Choose Role --')]</value>
      <webElementGuid>344a836d-a4d1-4874-873a-f4cdcfb8e69d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
