<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah                            In_244cf4</name>
   <tag></tag>
   <elementGuidId>4bfa27ef-7f5d-4dea-82bb-4b70c5ef0977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-pill.btn-air-primary.btn-outline-primary.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12d21d5a-55ff-446e-a171-4ac004495a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f45adf66-8492-4bc4-949b-dbc7a19e0a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-pill btn-air-primary btn-outline-primary text-white</value>
      <webElementGuid>560e2863-e80c-4b59-8a3f-689eaafa3813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>bbf23bb9-a88b-4719-9bca-9789ae2b8628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalAdd</value>
      <webElementGuid>1e312eea-f2dd-4c89-b84f-11a392738686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah
                            Introductory</value>
      <webElementGuid>df93ee58-2e2b-4ee7-8ab2-a898d8428419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageWrapper&quot;)/div[@class=&quot;page-body-wrapper null&quot;]/div[@class=&quot;page-body&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-header b-t-primary&quot;]/div[@class=&quot;btn-popup pull-right&quot;]/button[@class=&quot;btn btn-primary btn-pill btn-air-primary btn-outline-primary text-white&quot;]</value>
      <webElementGuid>997a28da-3d2b-4419-94c7-5f0fc89fcd56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>02c43f88-8c82-4605-b32d-2e1a094207c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageWrapper']/div[2]/div/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>6b30655f-454c-498d-b968-e84fb0c1a147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>bda145bf-73be-4cb5-a431-b992b30cd471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Tambah
                            Introductory' or . = ' Tambah
                            Introductory')]</value>
      <webElementGuid>b1380767-628e-4e46-ab6f-9f757db135e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
