<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_end</name>
   <tag></tag>
   <elementGuidId>a25d863a-7e99-4b58-ad2b-a33ea71d0545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endAdd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#endAdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d459f575-85f7-4010-a594-d6fc058a519e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>cf61212e-87a3-481f-80ea-7dc520ba7bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3958a301-1f2c-454b-95d2-81f2e504de24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endAdd</value>
      <webElementGuid>98c53a19-8b82-4819-bed0-413b5d7f1edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>15a90727-f27a-466c-83be-32e3606912ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>51e74b90-10d4-49fa-8c41-7877b7a7d997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2024-01-22T11:52</value>
      <webElementGuid>231bf5c6-4a3e-45d8-8b46-9c3a1b566c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endAdd&quot;)</value>
      <webElementGuid>738ae437-1221-4475-a745-c4b6ff93fa8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endAdd']</value>
      <webElementGuid>653343b6-ac1d-47a4-8da6-8b8505abaf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/input</value>
      <webElementGuid>7b3dee5f-60ec-4a80-a396-797a8efcd30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>dd123293-f65e-44a2-b7e7-c526ccccc7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'datetime-local' and @id = 'endAdd' and @name = 'end']</value>
      <webElementGuid>92776ccb-40b2-4e45-ae3b-29024a7b65b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
