<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin KAF_btnPrivileges</name>
   <tag></tag>
   <elementGuidId>797d0949-4cd8-4ace-9ceb-4bae472083e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='btnPrivileges'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22447117-3f3f-485c-90d7-458d64393b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://34.128.87.8:8082/roles/privileges/b0449a03-2da0-4e33-9c24-466d5330761b</value>
      <webElementGuid>561ed40e-9c49-45fe-bc7c-8f837d72d48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-xs btn-pill</value>
      <webElementGuid>751fd9dc-8c74-409a-a883-5eeb954bfde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPrivileges</value>
      <webElementGuid>42c67200-912b-4774-80ec-1b406e003de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Set Privileges</value>
      <webElementGuid>37d3a8cd-7302-45c4-9a08-c4610b94c107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role-table&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;text-center&quot;]/a[@id=&quot;btnPrivileges&quot;]</value>
      <webElementGuid>72b453a7-aaf5-4985-a794-38dde5cbe102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='btnPrivileges'])[4]</value>
      <webElementGuid>ba79ec7d-7e8b-4bc4-91e7-ab63b2560a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='role-table']/tbody/tr[4]/td/a</value>
      <webElementGuid>7eb115ce-e681-4651-96f0-f88db6eeeb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://34.128.87.8:8082/roles/privileges/b0449a03-2da0-4e33-9c24-466d5330761b']</value>
      <webElementGuid>36b46fd3-8c26-4d1c-9bba-ca58800fc2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/a</value>
      <webElementGuid>f8ae1235-9aba-43d9-9aeb-fda264cac0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://34.128.87.8:8082/roles/privileges/b0449a03-2da0-4e33-9c24-466d5330761b' and @id = 'btnPrivileges' and @title = 'Set Privileges']</value>
      <webElementGuid>45ce6975-b99e-480a-99dc-c9d067bc82cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
