<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_test katalon</name>
   <tag></tag>
   <elementGuidId>4f99fc41-c8d2-443a-8c8a-2b6b44ce7433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='role-table']/tbody/tr[4]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a3136da6-e52d-48b3-a0a9-b55efdbc71ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test katalon</value>
      <webElementGuid>09bb5158-8585-4935-a99c-fe09dfcd350d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role-table&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[2]</value>
      <webElementGuid>8eb160ea-fe80-45e5-bbc9-68ed44d9bcff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='role-table']/tbody/tr[4]/td[2]</value>
      <webElementGuid>333e0242-9dfc-437d-b810-23fb218af5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]</value>
      <webElementGuid>fc28aeea-d045-426a-87ce-4e9c8b2d5a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'test katalon' or . = 'test katalon')]</value>
      <webElementGuid>a20c7168-3fca-45bc-9d50-0429cffb9a8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
